ui: 'bdd'
timeout: 0
full-trace: true
color: true
inline-diffs: true
allow-uncaught: true
async-only: true
parallel: true
jobs: 5
spec:
  - 'tests/e2e/*.spec.js'
ignore:
  - 'tests/playwright_tests/*'
