ui: 'bdd'
timeout: 0
full-trace: true
color: true
inline-diffs: true
allow-uncaught: true
async-only: true
parallel: true
jobs: 10
reporter: mochawesome-screenshots
reporter-option:
  - 'framework=puppeteer'
  - 'reportPageTitle=Liquality Wallet Test Report'
  - 'reportTitle=Liquality Wallet Test Report'
  - 'shortScrFileNames=true'
  - 'passedScreenshot=true'
